# Generated by Django 3.2.5 on 2021-07-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
