# Generated by Django 3.2.5 on 2021-07-15 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_package_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='user',
            field=models.ManyToManyField(related_name='package_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
